project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "learnOrd"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/stefanocoretta/learnOrd"
    left:
      - href: index.qmd
        text: Home
      - href: code/slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



